service: aws-webpack-nodejs # NOTE: update this with your service name
# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
frameworkVersion: ">=1.26.1 <2.0.0"

custom:
  stage: ${file(stages/${opt:stage, self:provider.stage}.yml)}
# Add custom variables here. You can re-use variables defined in the stage yml
# customStageVar: ${self:custom.stage.customStageVar}
  webpack:
    includeModules:
      forceExclude:
        - aws-sdk

plugins:
  - serverless-webpack

package:
  individually: true

provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  region: ${opt:region, self:custom.stage.region}
  profile: ${self:custom.stage.profile}
  iamRoleStatements: ${file(config/iamRoleStatements.yml)}
  deploymentBucket:
    name: com.serverless.${self:custom.stage.profile}.${self:provider.region}.deploys

environment:
  SERVERLESS_REGION: ${self:provider.region}

functions: ${file(lib/config.js):functions}
resources:
  Resources: ${file(lib/config.js):resources}
